version: '3.8'
services:
    db:
        image: postgres:latest
        container_name: ${APP_NAME}.postgres.docker
        restart: always
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - ${DB_PORT}:5432
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local
